---
# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tsanghan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: ap-southeast-1
          role: arn:aws:iam::255945442255:role/cert-manager-20241002071843962400000014
          auth:
            kubernetes:
              serviceAccountRef:
                name: cert-manager